spring:
  datasource:
    url: jdbc:postgresql://dpg-d0utd6ili9vc73eq2db0-a.ohio-postgres.render.com:5432/postgresql_patamansa
    username: postgresql_patamansa_user
    password: x8lW0WkuJtyIlk2Bc7JACvn0dw12QKkb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
